# permissions for end users to edit checkdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkdeploy-editor-role
rules:
- apiGroups:
  - core.example.com
  resources:
  - checkdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.example.com
  resources:
  - checkdeploys/status
  verbs:
  - get
